Repository Part3-Team13-Taskify/Taskify, pull requests merged in 2024-04, with the labels that each got.

#8 ✨Feat: button components
  public/assets/icon/arrow.svg
  public/assets/icon/arrowForward.svg
  public/assets/icon/arrowReverse.svg
  src/components/common/button/index.tsx
  src/styles/reset.css
Labels: components

#11 ♻️ Refactor : input components
  src/components/common/input/passwordInput/index.tsx
Labels: 컴포넌트

#15 ✨ Feat: navigation components
  public/assets/icon/vector.svg
  src/components/common/navigation/index.tsx
Labels: 컴포넌트

#18 ✨Feat: addColumnModal, editColumnModal, deleteColumnModal UI
  package-lock.json
  package.json
  src/components/ColumnModal/addColumnModal/index.tsx
  src/components/ColumnModal/deleteColumnModal/index.tsx
  src/components/ColumnModal/editColumnModal/index.tsx
  src/components/common/modal/index.tsx
  src/components/example/exampleModal/index.tsx
Labels: 컴포넌트, 기능, 스타일

#21 ✨ Feat: button twMerge 기능 추가
  src/components/common/button/index.tsx
Labels: 기능

#23 ✨Feat: 할 일 카드 모달, 할 일 생성 모달 UI 구현
  public/assets/card/exampleChip/chip/doneLarge.svg
  public/assets/card/exampleChip/chip/progressLarge.svg
  public/assets/card/exampleChip/chip/todoLarge.svg
  public/mock/Comment.json
  public/mock/TaskCard.json
  src/components/Reply.tsx
  src/components/TaskLabel.tsx
  src/components/TaskModal/CreateTask.tsx
  src/components/TaskModal/TaskCard.tsx
  tsconfig.json
Labels: 컴포넌트

#24 ✨ Feat: addDashboardModal UI
  src/components/common/dashboardcolorpicker/index.tsx
  src/components/dashboardModal/addDashboardModal/index.tsx
  src/components/mydashboard/InvitationDashboard.tsx
  src/pages/mydashboard/index.tsx
Labels: 기능, 스타일

#25 ✨ Feat: signin page UI
  .eslintrc.json
  src/components/common/header/index.tsx
  src/components/common/input/emailInput/index.tsx
  src/components/common/input/passwordInput/index.tsx
  src/components/common/signModal/index.tsx
  src/components/landing/Content.tsx
  src/pages/signin/index.tsx
  src/styles/globals.css
Labels: 스타일, 페이지

#29 ✨ Feat: mypage UI
  src/components/mypage/index.tsx
Labels: 스타일

#30 ✨ 할 일 수정하기 모달 UI 구현
  src/components/TaskModal/EditTask.tsx
Labels: 컴포넌트

#32 ✨ Feat: mypage사진 기능 추가, Input components 재정의
  src/components/common/input/emailInput/index.tsx
  src/components/common/input/index.tsx
  src/components/common/input/passwordInput/index.tsx
  src/components/mypage/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: 컴포넌트, 기능, 스타일, 페이지

#33 ✨Feat: columns 생성 기능 구현
  .eslintrc.json
  src/api/columnsApi.ts
  src/components/ColumnModal/addColumnModal/index.tsx
  src/components/ColumnModal/editColumnModal/index.tsx
  src/components/common/modal/index.tsx
  src/components/dashboard/ColumnsList.tsx
  src/util/axios.ts
Labels: 기능

#34 ✨Feat: dashboard edit api
  src/components/common/colorpicker/index.tsx
  src/components/common/input/index.tsx
  src/components/dashboardEdit/Dashboard.tsx
  src/util/axios.ts
Labels: 기능

#36 ✨ Feat: signinPage
  src/api/userApi.ts
  src/components/common/signModal/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: 기능, 페이지

#35 ✨Feat: sidebar api
  src/components/common/sidebar/index.tsx
Labels: 기능

#38 ✨ Feat: InvitationTable UI
  src/components/mydashboard/InvitationDashboard.tsx
  src/components/mydashboard/table/InvitaionList.tsx
  src/components/mydashboard/table/InvitationSearch.tsx
  src/components/mydashboard/table/index.tsx
Labels: 스타일

#37 ♻️Refactor: TaskCard 컴포넌트 api 연결 구현
  src/components/TaskModal/CreateTask.tsx
  src/components/TaskModal/EditTask.tsx
  src/components/TaskModal/TaskCard.tsx
Labels: 컴포넌트

#40 ♻️ Refactor: addColumnModal input components 적용
  src/api/columnsApi.ts
  src/components/ColumnModal/addColumnModal/index.tsx
  src/components/dashboard/ColumnsList.tsx
  src/components/example/exampleModal/index.tsx
Labels: 기능, 리팩토링

#41 ✨ Feat: signup Page
  src/components/common/input/passwordInput/index.tsx
  src/components/mypage/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/util/axios.ts
Labels: 기능, 페이지

#43 🐛 Fix: axios, Api
  src/pages/api/userApi.ts
  src/pages/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/util/axios.ts
Labels: 기능, 리팩토링

#44 ✨Feat: ColumnList API 연결
  public/assets/chip/ellipseVioletSmall.svg
  src/api/columnsApi.ts
  src/components/ColumnModal/addColumnModal/index.tsx
  src/components/common/button/index.tsx
  src/components/dashboard/ColumnsList.tsx
  src/pages/dashboard/[id].tsx
  tailwind.config.ts
Labels: 기능, 스타일, 리팩토링

#45 ✨ Feat: 초대목록 조회 API
  src/components/mydashboard/InvitationDashboard.tsx
  src/components/mydashboard/table/index.tsx
  src/pages/api/getInvitationApi.ts
Labels: 기능

#46 ✨Feat: sidebar pagination
  src/components/common/modalColorPicker/index.tsx
  src/components/common/navigation/Members.tsx
  src/components/common/navigation/index.tsx
  src/components/common/sidebar/DashboardList.tsx
  src/components/common/sidebar/DashboardListItem.tsx
  src/components/common/sidebar/Pagination.tsx
  src/components/common/sidebar/index.tsx
  src/components/dashboardEdit/Dashboard.tsx
  src/components/dashboardModal/addDashboardModal/index.tsx
  src/pages/api/dashboardEditApi.ts
  src/util/zustand.ts
Labels: 기능, 리팩토링

#48 Feat/pagination
  src/components/common/navigation/Members.tsx
  src/components/common/sidebar/DashboardList.tsx
  src/components/common/sidebar/DashboardListPagination.tsx
  src/components/dashboardEdit/Dashboard.tsx
  src/components/dashboardEdit/table/InviteePagination.tsx
  src/components/dashboardEdit/table/MembersPagination.tsx
  src/components/dashboardEdit/table/TableHeader.tsx
  src/pages/api/dashboardEditApi.ts
  src/util/zustand.ts
Labels: 기능, 오류, 리팩토링

#49 ✨Feat: 컬럼 삭제, 수정, 추가 기능 구현
  src/components/ColumnModal/addColumnModal/index.tsx
  src/components/ColumnModal/deleteColumnModal/index.tsx
  src/components/ColumnModal/editColumnModal/index.tsx
  src/components/common/input/index.tsx
  src/components/dashboard/ColumnsList.tsx
  src/components/dashboard/addColumnButton/index.tsx
  src/components/dashboard/columnList/index.tsx
  src/components/dashboard/editColumnButton/index.tsx
  src/components/dashboard/scrollButton/index.tsx
  src/pages/api/columnsApi.ts
  src/pages/dashboard/[id].tsx
Labels: 기능, 스타일

#50 ✨Feat: invite modal
  src/components/InviteModal/index.tsx
  src/components/common/navigation/index.tsx
  src/components/common/sidebar/DashboardList.tsx
  src/components/common/sidebar/index.tsx
  src/components/dashboardEdit/Dashboard.tsx
  src/components/dashboardEdit/table/MembersPagination.tsx
  src/pages/api/dashboardEditApi.ts
  src/util/zustand.ts
Labels: 컴포넌트, 기능, 오류

#51 ✨ Feat: 초대목록 무한스크롤, 초대목록 유무에 따라 UI 다르게
  src/components/mydashboard/InvitationDashboard.tsx
  src/components/mydashboard/table/index.tsx
  src/pages/api/getInvitationApi.ts
  src/pages/api/putInvitationApi.ts
Labels: 기능, 스타일

#52 🐛 Fix: conditionally render profile image
  faker.tsx
  src/components/common/navigation/Members.tsx
  src/components/common/sidebar/index.tsx
Labels: 오류

#53 ✨ Feat: myPage API연동 + 기능구현
  src/components/common/signModal/index.tsx
  src/components/mypage/index.tsx
  src/components/mypage/passwordchange.tsx
  src/components/mypage/profile.tsx
  src/pages/api/mypageApi.ts
Labels: 기능, 스타일, 페이지

#55 ✨Feat: 할일 수정 요청 구현
  src/components/TaskModal/CreateTask.tsx
  src/components/TaskModal/EditTask.tsx
  src/components/TaskModal/TaskCard.tsx
  src/components/TaskModal/TaskLabel.tsx
  src/components/dashboard/columnList/index.tsx
Labels: 컴포넌트, 리팩토링

#56 ✨ Feat: Logout
  src/components/common/navigation/index.tsx
  src/components/common/navigation/logout.tsx
Labels: 기능

#57 ✨Feat: psuedo profile image if no profile image
  package-lock.json
  package.json
  src/components/InviteModal/index.tsx
  src/components/common/navigation/Dropdown.tsx
  src/components/common/navigation/MyProfile.tsx
  src/components/common/navigation/index.tsx
  src/components/dashboardModal/addDashboardModal/index.tsx
Labels: 기능

#60 ✨ Feat: profileimg 수정+구현
  src/components/mypage/profile.tsx
  src/pages/api/mypageApi.ts
Labels: 기능, 스타일, 오류

#61 ♻️Refactor: custom hook to manage global states for invitees, members, and dashboard list
  src/components/InviteModal/index.tsx
  src/components/common/colorpicker/index.tsx
  src/components/common/layout/index.tsx
  src/components/common/navigation/InitialImage.tsx
  src/components/common/navigation/Members.tsx
  src/components/common/navigation/MyProfile.tsx
  src/components/common/navigation/index.tsx
  src/components/common/sidebar/DashboardList.tsx
  src/components/common/sidebar/DashboardListItem.tsx
  src/components/common/sidebar/DashboardListPagination.tsx
  src/components/dashboardEdit/Dashboard.tsx
  src/components/dashboardEdit/table/InviteePagination.tsx
  src/components/dashboardEdit/table/MembersPagination.tsx
  src/components/dashboardEdit/table/TableList.tsx
  src/components/dashboardModal/addDashboardModal/index.tsx
  src/hooks/useDashboardList.tsx
  src/hooks/useInvitees.ts
  src/hooks/useMembers.tsx
  src/pages/api/dashboardEditApi.ts
  src/pages/dashboard/[id].tsx
  src/pages/dashboard/[id]/edit.tsx
  src/pages/my-dashboard/index.tsx
  src/pages/my-page/index.tsx
  src/util/zustand.ts
Labels: 기능, 오류, 리팩토링

#63 ✨ Feat: HOC(withauth)
  next.config.mjs
  src/components/common/hocs/withAuth.tsx
  src/components/common/input/exampleInput.tsx
  src/components/common/navigation/Dropdown.tsx
  src/components/common/navigation/Members.tsx
  src/components/common/navigation/index.tsx
  src/components/dashboardEdit/Dashboard.tsx
  src/components/mypage/profile.tsx
  src/hooks/useDashboardList.ts
  src/hooks/useInvitees.ts
  src/hooks/useMembers.ts
  src/pages/api/columnsApi.ts
  src/pages/api/dashboardEditApi.ts
  src/pages/api/getInvitationApi.ts
  src/pages/api/mypageApi.ts
  src/pages/api/putInvitationApi.ts
  src/pages/dashboard/[id].tsx
  src/pages/dashboard/[id]/edit.tsx
  src/pages/my-dashboard/index.tsx
  src/pages/my-page/index.tsx
Labels: 기능, 오류, 리팩토링

#69 ✨Feat: draggable dashboard in sidebar
  package-lock.json
  package.json
  src/components/common/navigation/Members.tsx
  src/components/common/navigation/MyProfile.tsx
  src/components/common/sidebar/DashboardList.tsx
  src/components/common/sidebar/DashboardListItem.tsx
Labels: 기능, 오류

#70 🐛Fix: errors before build
  src/components/dashboard/addColumnButton/index.tsx
  src/components/dashboard/editColumnButton/index.tsx
  src/components/mypage/profile.tsx
  src/pages/api/columnsApi.ts
Labels: 오류

#73 ✨Feat: CardList 무한스크롤 구현
  .eslintrc.json
  src/components/common/button/index.tsx
  src/components/common/card/index.tsx
  src/components/common/layout/index.tsx
  src/components/dashboard/cardList/index.tsx
  src/components/dashboard/columnList/index.tsx
  src/components/mydashboard/InvitationDashboard.tsx
  src/components/mydashboard/MyDashboardList.tsx
  src/components/mydashboard/MyDashboardListItem.tsx
  src/pages/api/cardListApi.ts
  src/util/zustand.ts
Labels: 기능, 스타일, 리팩토링

#75 ✨Feat: invite modal member options
  src/components/InviteModal/index.tsx
  src/components/TaskModal/TaskCard.tsx
  src/components/common/card/index.tsx
  src/components/common/input/index.tsx
  src/components/common/navigation/Members.tsx
  src/components/common/navigation/MyProfile.tsx
  src/components/common/navigation/index.tsx
  src/components/common/sidebar/DashboardList.tsx
  src/components/common/sidebar/DashboardListItem.tsx
  src/components/common/sidebar/DashboardListPagination.tsx
  src/components/common/sidebar/index.tsx
  src/components/dashboardEdit/Dashboard.tsx
  src/components/dashboardEdit/table/TableList.tsx
  src/components/dashboardEdit/table/index.tsx
  src/components/mypage/index.tsx
  src/components/mypage/profile.tsx
  src/util/zustand.ts
Labels: 컴포넌트, 기능, 오류

#76 🐛Fix: cardList 불러오기 기능 수정
  src/components/TaskModal/CreateTask.tsx
  src/components/TaskModal/EditTask.tsx
  src/components/TaskModal/TaskCard.tsx
  src/components/common/card/index.tsx
  src/components/common/chip/index.tsx
  src/components/dashboard/cardList/index.tsx
  src/components/dashboard/columnList/index.tsx
  src/components/mydashboard/InvitationDashboard.tsx
  src/pages/api/cardListApi.ts
Labels: 기능, 스타일, 리팩토링

#78 ♻️Refactor: 프로필이미지를 위한 Image -> img로 변경
  src/components/TaskModal/EditTask.tsx
  src/components/TaskModal/TaskCard.tsx
  src/components/common/card/index.tsx
  src/components/common/navigation/Members.tsx
  src/components/common/navigation/MyProfile.tsx
  src/components/mypage/profile.tsx
Labels: 리팩토링

#79 ♻️Refactor: Image -> img
  .eslintrc.json
  src/components/TaskModal/CreateTask.tsx
Labels: 리팩토링

#81 ♻️Refactor: 카드 수정, 삭제, 생성 시 대시보드 리렌더 구현
  src/components/TaskModal/Comments.tsx
  src/components/TaskModal/CreateTask.tsx
  src/components/TaskModal/DeleteTask.tsx
  src/components/TaskModal/EditTask.tsx
  src/components/TaskModal/Reply.tsx
  src/components/TaskModal/TaskCard.tsx
  src/components/common/card/index.tsx
  src/components/dashboard/cardList/index.tsx
  src/components/dashboard/columnList/index.tsx
  src/pages/api/comments.ts
  src/pages/api/taskModalApi.ts
  src/util/zustand.ts
Labels: 컴포넌트, 기능, 리팩토링

#82 ♻️ Refator: 주석 + CSS 수정
  src/components/mypage/passwordchange.tsx
  src/components/mypage/profile.tsx
  src/pages/_app.tsx
  src/pages/signin/index.tsx
  src/util/axios.ts
Labels: 스타일
